### ISSUE TITLE
Hello.ts Change

### ISSUE THREAD

**Issue by EisenbergEffect** [Layoric/AureliaExample#1]
In the `hello.ts` file, consider changing the code to this:

```
import {bindable, autoinject} from "aurelia-framework";
import {HttpClient} from "aurelia-http-client";

@autoinject()
export class HelloCustomElement {
    result: string;
    @bindable name: string;

    constructor(private httpClient: HttpClient) {
        this.httpClient.configure(config => {
            config.withHeader('Accept', 'application/json');
        });
    }

    nameChanged(newValue) {
        if (newValue.length > 0) {
            this.httpClient.get('/hello/' + newValue).then((response) => {
                this.result = response.content.Result;
            });
        } else {
            this.result = '';
        }
    }
}
```

**Comment by EisenbergEffect** [comment]
Note that you could also use `@observable` instead of `@bindable` in this case since your class isn't functioning as a custom element, but just a plain view-model.

**Comment by Layoric** [comment]
Thanks @EisenbergEffect ! :+1: That has given me a better understanding of the two decorators. 

I've added some separate views for the router and kept `hello.ts` as a custom element with `@binding` using it in the views imported via `<require from="./hello"></require>`. Below is `app.ts`.

``` typescript
    router: Router;

    configureRouter(config, router: Router) {
        config.title = 'Aurelia';
        config.map([
            { route: ['', 'home'], name: 'home', moduleId: './home', nav: true, title: 'Home' },
            { route: ['/view1', 'view1'], name: 'view1', moduleId: './view1', nav: true, title: 'View 1' },
            { route: ['/view2', 'view2'], name: 'view2', moduleId: './view2', nav: true, title: 'View 2' }
        ]);

        this.router = router;
    }
```

And `home.html` using `hello` custom element without providing `name` attribute. Other views do provide `name` attribute with fixed value to show alternate use. Below is `home.html`.

```
<template>
    <require from="./hello"></require>
    <h2>${message}</h2>

    <hello></hello>
</template>
```

Is this reasonable?

The update event by convention is a nicer way of hooking into an `OnChange` event as well. 

If there are any recommended project structure guidelines/examples for Aurelia, happy to structure `src` directory in that way, but flat is simple for now.

Appreciate the feedback, thanks!

**Comment by EisenbergEffect** [comment]
Yes, that sounds good. We do have a standard structure we are working towards via our new cli. We could chat about that more if you are interested.

**Comment by Layoric** [comment]
Sounds interesting, would be good if template could match so that those who use it can start using the cli once it's ready. Feel free to send me any details, I'll do my best to incorporate your recommendations into the template.

We still have an [outstanding issue for those using ReSharper](https://youtrack.jetbrains.com/issue/RSRP-458759), hoping it will be fixed soon, but not sure on timeframe for next ReSharper release, so template **probably** won't be released until this fix is at least on the known horizon.

**Comment by EisenbergEffect** [comment]
If you would like, you can do this:
- run `npm install -g aurelia-cli` to install the _very_ alpha cli
- run `aurelia new` to create a new app
- enter a project name and follow the prompts; only select the default option; that's all that works

This will generate a folder structure for you and you can use that as a basis for how we will be recommending that developers organize their Aurelia projects. Let me know if you have any questions.

**Comment by Layoric** [comment]
Excellent, I'll give it a go and let you know :+1:

**Comment by Layoric** [comment]
Trying to translate the structure for use in JSPM + TypeScript app , just so I understand, is the recommendation to have application reusable components is a `resources` feature? Eg, custom elements etc? If so, where would be the standard structure to place views? `src/views` or as a part of the `resources` feature? eg `src/resources/views` or doesn't really matter?

**Comment by EisenbergEffect** [comment]
- resources is for shared view resources like elements, etc.
- under source, we would favor a "feature-based" organization; one folder per application feature with all views and view-models contained in that folder

**Comment by Layoric** [comment]
:+1: Thanks for the tips, I'll add a default `resources` feature with shared `hello` element.
